1C-clusters:
  - &1cfreshl
    host: 10.70.3.11
    port: 1541
    admin_username: adm
    admin_pwd: 123123123
  - &ubuntu-srvr-1
    host: 10.70.5.103
    port: 1541
    admin_username: ""
    admin_pwd: ""
infobases:
  - &TestIB
    cluster: *1cfreshl
    name: test_ibase
    username: ""
    pwd: ""
  - &TestCenter
    cluster: *1cfreshl
    name: test_center_1
    username: ""
    pwd: ""
  - &WorkInServiceModel
    cluster: *1cfreshl
    name: work_in_service_model_demo
    username: adm
    pwd: 123123123
  - &SM-UbuntuServer1
    cluster: *ubuntu-srvr-1
    name: sm-ubuntu-srvr-1
    username: adm
    pwd: 111
