version: 0.0.0.1
command-type: platform-update
script-name: platform_update.py
external-values:
  - new-version
default-values:
  server-role: app
  test-mode: false
  zone: production
  old-version: ""
  distr-folder: /media/shared/AutomationLibraryDemo/1c_distr/linux/RPM/x86_64
  setup-folder: ""
  timeout: 30
  try-count: 3
  time-limit: 3600
  clean-snccntx: true
  clean-temp: true
  clean-pfl: true
  download-tmp-folder: ./temp_rpm
  cluster-folder: "/var/1C/srvinfo"
  cluster-debug: False
  cluster-debug: False
  dumps-folder: dumps
  service-1c:
    name: srv1cv8
    login: usr1cv8
    password: 111
  ras:
    name: srv1cv8-ras
    path: /opt/1C/v8.3/x86_64
    port: 4540
    login: usr1cv8
    password: 111
  web-library:
    path: /opt/1C/v8.3/x86_64/wsap24.so
