version: 0.0.0.1
command-type: execute-epf
script-name: execute-epf.py
external-values:
  - srvr
  - ib
  - cf-name
default-values:
  usr: ""
  pwd: ""
  test-mode: false
  zone: production
  try-count: 1
  timeout: 100
  time-limit: 3600
  lang: ru
  client-path: C:\Program Files (x86)\1cv8\8.3.10.2466\bin
  distr-folder: C:\Users\Kononov_A\AppData\Roaming\1C\1cv8\tmplts\1c\SM\1_0_71_36\
  backup-folder: C:\1c_backups
